version: '3.8'

services:
  ghost-dev:
    image: ghost:latest
    ports:
      - "3000:2368"
    volumes:
      - ghost_dev_content:/var/lib/ghost/content
    environment:
      url: http://localhost:3000/

  ghost-prod:
    image: ghost:latest
    ports:
      - "2368:2368"
    volumes:
      - ghost_prod_content:/var/lib/ghost/content
    environment:
      url: http://localhost:2368/

  db-dev:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb_dev
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql_dev_data:/var/lib/mysql

  db-prod:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb_prod
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - mysql_prod_data:/var/lib/mysql

volumes:
  ghost_dev_content:
  ghost_prod_content:
  mysql_dev_data:
  mysql_prod_data:
